### ISSUE TITLE
headings in org-mode 

### ISSUE THREAD

**Issue by xieyuheng** [hbin/molokai-theme#3]
你好 :)
我很喜歡你的這個配色
但是在 org-mode 中使用的時候
會出現我所不希望的效果 
請實驗下面的語法高亮 :

```
* heading-level-1
** heading-level-2
*** heading-level-3
**** heading-level-4
***** heading-level-5
****** heading-level-6
******* heading-level-6
```

其中 
heading-level-3 會被渲染成粗體 (我希望它能不是粗體)
heading-level-4 會被渲染成根註釋一樣的顏色 (我不希望註釋的顏色出現在 heading 的高亮中)
heading-level-5 也會別渲染成粗體

不知道這些效果是否就是你的設計意圖?
我能否更改這些效果? 
我該如何更改?
或者 這些效果根本就不是你所能控制的 而是 org-mode 所決定的 ?

期待你的幫助 :)

**Comment by xieyuheng** [comment]
另外你可以發現
我的網站就是利用你的配色生成的 ::

http://the-little-language-designer.github.io/cicada-nymph/intro/show-all.html

 我應該在鳴謝裏 加上對你的感謝才對 ^-^

**Comment by hbin** [comment]
非常抱歉，才看您的问题。

当时写这个主题是因为我看到 Vim 有个叫 [molokai](https://github.com/tomasr/molokai) 的主题，自己很喜欢，而 Melpa 中的几个类似 molokai 的主题都不是很满意，就自己重写了。在完成对主要语法的颜色支持后，便没有再进行后续开发:flushed:。

以下对您的问题回复：
1. 这不是我的设计意图，而是当时并没有考虑到支持 org-mode。
2. 您可以 fork 当前项目任意修改。当然，欢迎您修改之后提 PR。
3. 您可以参考 [bbatsov](https://github.com/bbatsov) 的 [zenburn](https://github.com/bbatsov/zenburn-emacs/blob/master/zenburn-theme.el#L723-L762) 主题针对 org-mode 进行修改。这里还有一篇 [bbatsov](https://github.com/bbatsov) 写的关于如何编写 Emacs theme 的文章，供您参考：http://batsov.com/articles/2012/02/19/color-theming-in-emacs-reloaded。
4. 如上，org-mode 默认使用 [font-lock](https://github.com/hbin/molokai-theme/blob/master/molokai-theme.el#L83-L98) 的值，您可以参照 [zenburn](https://github.com/bbatsov/zenburn-emacs/blob/master/zenburn-theme.el#L723-L762) 进行修改。

非常高兴您喜欢这个主题

**Comment by xieyuheng** [comment]
我可以改 org-mode 的顏色了 :)
我的 fork 改了太多的東西 也許不適合 PR 了
也許我會以你的代碼爲基礎做個 cicada-theme

**Comment by xieyuheng** [comment]
另外

你現在不用這個主題了 ?
現在用 zenburn 嘛 ?

還有有關 顏色搭配的文章分享嘛 ?
低對比度的優點真的有心理學和生理學依據 ?
還是純屬個人喜好而已 ?

**Comment by hbin** [comment]
当然可以。

我现在就是用这个主题，见我的 [Emacs 配置](https://github.com/hbin/prelude/blob/master/personal/hbin-ui.el#L54-L57)。

:flushed: 你这个问题好深奥，纯属个人喜好，瞎折腾，并没有什么科学依据。

**Comment by xieyuheng** [comment]
在給自己的 mode 設計配色的時候
不應該直接使用顏色代碼 而應該服從 全局的 theme 
應該怎麼做到這一點?

**Comment by xieyuheng** [comment]
closing old issues :)
